[dosbox]
machine=vgaonly
language=
captures=capture
memsize=2

[cpu]
core=normal
fpu=auto
cputype=486
#cycles=12000
cycles=33445

[sblaster]
# uncomment these to test pc speaker audio
#sbtype=none
#oplmode=none
